--- #YAML:1.0
name:                 VCS-Lite
version:              0.11
abstract:             A minimal version control system
author:
  - Barbie <barbie@cpan.org>

license:              artistic_2
distribution_type:    module
installdirs:          site

requires:
  perl:                     5.006
  Algorithm::Diff:          1.13
  Carp:                     0
  Getopt::Long:             0
recommends:
  Test::CPAN::Meta:         0
  Test::CPAN::Meta::JSON:   0
  Test::Pod:                1.00
  Test::Pod::Coverage:      0.08
build_requires:
  IO::File:                 0
  Test::More:               0.70

provides:
  VCS::Lite:
    file:     lib/VCS/Lite.pm
    version:  0.11
  VCS::Lite::Delta:
    file:     lib/VCS/Lite/Delta.pm
    version:  0.11
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=VCS-Lite
  repository: http://github.com/barbie/vcs-lite

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Barbie's Brain 1.0
