# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         VCS-Lite
version:      0.08
version_from: lib/VCS/Lite.pm
installdirs:  site
requires:
    Algorithm::Diff:               1.13

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
